### ISSUE TITLE
Python package works with sage python, but Sage package fails to load

### ISSUE THREAD

**Issue by antonleykin** [Macaulay2/M2#1022]
This is related to
https://github.com/sagemath/cysignals/issues/115

If M2 is compiled `--with-python` in `sage -sh`, the package `Python` works... but `Sage` fails to load.

```
i1 : needsPackage "Sage"
-- success: python is present
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "", line 1, in <module>
    
  File "/Users/leykin/R/sage/local/lib/python2.7/site-packages/sage/all.py", line 77, in <module>
    from cysignals.signals import (AlarmInterrupt, SignalError,
  File "/Users/leykin/R/sage/local/lib/python2.7/site-packages/cysignals/__init__.py", line 3, in <module>
    init_cysignals()
  File "src/cysignals/signals.pyx", line 251, in cysignals.signals.init_cysignals
ValueError: signal only works in main thread
../../../../M2-anton/M2/Macaulay2/packages/Sage.m2:5:6:(2):[10]: error: python error
```

**Comment by antonleykin** [comment]
@dimpase

**Comment by d-torrance** [comment]
This was fixed at some point, as everything works with Sage 10.9:

```m2
 i1 : needsPackage "Python";

i2 : sys = import "sys";

i3 : sys@@"path"@@append "/var/tmp/sage-10.9-current/local/lib/python3.14/site-packages";

i4 : sage = import "sage.all";

i5 : n = sage@@Integer 2^67 - 1

o5 = 147573952589676412927

o5 : PythonObject of class sage.rings.integer.Integer

i6 : sage@@factor n

o6 = 193707721 * 761838257287

o6 : PythonObject of class sage.structure.factorization_integer.IntegerFactorization

i7 : M = sage@@matrix(sage@@QQ, {{1, 2}, {3, 4}})

o7 = [1 2]
     [3 4]

o7 : PythonObject of class sage.matrix.matrix_rational_dense.Matrix_rational_dense

i8 : M@@determinant()

o8 = -2

o8 : PythonObject of class sage.rings.rational.Rational

i9 : M@@charpoly()

o9 = x^2 - 5*x - 2

o9 : PythonObject of class sage.rings.polynomial.polynomial_rational_flint.Polynomial_rational_flint

i10 : M@@inverse()

o10 = [  -2    1]
      [ 3/2 -1/2]

o10 : PythonObject of class sage.matrix.matrix_rational_dense.Matrix_rational_dense
```
