### ISSUE TITLE
Invalid vector access when building CotangentSchubert examples

### ISSUE THREAD

**Issue by jamesjer** [Macaulay2/M2#2513]
I did a test build of Macaulay 1.20 for Fedora.  The build failed here:
```
 -- making example result files in ../../../usr-dist/common/share/doc/Macaulay2/CotangentSchubert/example-output/
 -- making example results for "basisCoeffs"                                
 ulimit -c unlimited; ulimit -t 700; ulimit -m 850000; ulimit -s 8192; ulimit -n 512;  cd /tmp/M2-196276-0/1-rundir/; GC_MAXIMUM_HEAP_SIZE=400M "/builddir/build/BUILD/M2-release-1.20/M2/BUILD/x86_64-redhat-linux-gnu/usr-dist/x86_64-Linux-Fedora-37/bin/M2-binary" -q --int --no-randomize --no-readline --silent --stop --print-width 77 -e 'needsPackage("CotangentSchubert",Reload=>true,FileName=>"/builddir/build/BUILD/M2-release-1.20/M2/Macaulay2/packages/CotangentSchubert.m2")' <"/tmp/M2-196276-0/0_basis__Coeffs.m2" >>"/builddir/build/BUILD/M2-release-1.20/M2/BUILD/x86_64-redhat-linux-gnu/usr-dist/common/share/doc/Macaulay2/CotangentSchubert/example-output/_basis__Coeffs.errors" 2>&1
/builddir/build/BUILD/M2-release-1.20/M2/BUILD/x86_64-redhat-linux-gnu/usr-dist/common/share/doc/Macaulay2/CotangentSchubert/example-output/_basis__Coeffs.errors:0:1: (output file) error: Macaulay2 killed by signal 6
/tmp/M2-196276-0/0_basis__Coeffs.m2:0:1: (input file)
M2: *** Error 6
 -- 1.12171 seconds elapsed
 -- storing example results in ../../../usr-dist/common/share/doc/Macaulay2/CotangentSchubert/example-output/_basis__Coeffs.out
 -- warning: missing file /builddir/build/BUILD/M2-release-1.20/M2/BUILD/x86_64-redhat-linux-gnu/usr-dist/common/share/doc/Macaulay2/CotangentSchubert/example-output/_basis__Coeffs.out
 -- making example results for "segreClass"                                  -- 0.470983 seconds elapsed
 -- storing example results in ../../../usr-dist/common/share/doc/Macaulay2/CotangentSchubert/example-output/_segre__Class.out
 -- making example results for "setupCotangent"                              -- 0.46879 seconds elapsed
 -- storing example results in ../../../usr-dist/common/share/doc/Macaulay2/CotangentSchubert/example-output/_setup__Cotangent.out
 -- making example results for "chernClass"                                  -- 0.517161 seconds elapsed
 -- storing example results in ../../../usr-dist/common/share/doc/Macaulay2/CotangentSchubert/example-output/_chern__Class.out
 -- making example results for "puzzle"                                      -- 0.48721 seconds elapsed
 -- storing example results in ../../../usr-dist/common/share/doc/Macaulay2/CotangentSchubert/example-output/_puzzle.out
 -- warning: installPackage: 1 error(s) occurred running examples for package CotangentSchubert:

_basis__Coeffs.errors
*********************
-- -*- M2-comint -*- hash: -851684972

i1 : (A,B,FF,I)=setupCotangent(2,4,Presentation=>Borel,Ktheory=>true,Equivariant=>false)

o1 = (A, B, FF, {0011, 0101, 0110, 1001, 1010, 1100})

o1 : Sequence

i2 : basis A
/usr/include/c++/12/bits/stl_vector.h:1142: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = const int*; _Alloc = gc_allocator<const int*>; const_reference = const int* const&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

That assertion is active because Fedora builds with `-D_GLIBCXX_ASSERTIONS`.  The assertion failure means that an invalid vector element was accessed.  GDB says:
```
(gdb) bt
#0  0x00007ffff6da4d1c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff6d54a56 in raise () from /lib64/libc.so.6
#2  0x00007ffff6d3e7f4 in abort () from /lib64/libc.so.6
#3  0x00007ffff6fc9ea0 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) ()
   from /lib64/libstdc++.so.6
#4  0x0000000000745de1 in std::vector<int const*, gc_allocator<int const*> >::operator[] (this=<optimized out>, 
    __n=<optimized out>) at /usr/include/c++/12/bits/stl_vector.h:1142
#5  std::vector<int const*, gc_allocator<int const*> >::operator[] (this=<optimized out>, __n=<optimized out>)
    at /usr/include/c++/12/bits/stl_vector.h:1140
#6  Monoid::degree_of_var (v=<optimized out>, this=<optimized out>) at ../../../../Macaulay2/e/monoid.hpp:115
#7  KBasis::KBasis (this=0x7fffab7a2180, bottom=0x7fffaefaa820, lo_degree0=<optimized out>, 
    hi_degree0=<optimized out>, heft_vector0=<optimized out>, vars0=<optimized out>, do_truncation0=false, limit0=-1)
    at ../../../../Macaulay2/e/matrix-kbasis.cpp:149
#8  0x0000000000746b15 in KBasis::k_basis (bottom=0x7fffaefaa820, lo_degree=0x7fffacd514e0, hi_degree=<optimized out>, 
    heft=0x7fffacd51500, vars=0x7fffaf629380, do_truncation=<optimized out>, limit=-1)
    at ../../../../Macaulay2/e/matrix-kbasis.cpp:517
#9  0x00000000008f448b in interface_rawBasis (e=0x7fffae8128c0) at ../../../../Macaulay2/d/interface.dd:2477
#10 interface_rawBasis (e=0x7fffae8128c0) at ../../../../Macaulay2/d/interface.dd:2469
[frames past here are not relevant]
```
In frame 7, we have:
```
i = 1
vars = {len = 4, array = {0}}
```

Looking inside `M` shows that `degree_of_var_` is a vector of length and capacity 1, containing a single NULL.  This code in matrix-kbasis.cpp, lines 146-153:
```
  for (int i = 0; i < vars->len; i++, next += heft_vector->len)
    {
      int v = vars->array[i];
      D->to_expvector(M->degree_of_var(v), exp);
      var_wts[i] = ntuple::weight(heft_vector->len, exp, heft_vector);
      if (var_wts[i] == 0) weight_has_zeros = true;
      ntuple::copy(heft_vector->len, exp, var_degs + next);
    }
```
therefore attempts to read beyond the size of that vector when it calls `M->degree_of_var(v)`.

**Comment by DanGrayson** [comment]
This is an excellent bug report.

@mikestillman

**Comment by mikestillman** [comment]
I agree, nice bug report!

**Comment by DanGrayson** [comment]
Jay, are you willing to make a pull request for your suggested change?

**Comment by jamesjer** [comment]
I should have mentioned that https://github.com/Macaulay2/M2/pull/2536 does in fact lead to a good build.  Thank you, @jkyang92 .
