### ISSUE TITLE
bug evoked by NumericalImplicitization

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#788]
This involves an example, which has been crashing overnight.  Memory is being scribbled on, and the garbage collector detects that when I compile in "debug" mode.
```
Macaulay2, version 1.11.1
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, PrimaryDecomposition, ReesAlgebra, TangentCone

i1 : input "~/src/M2/overnight/bug.m2"

ii2 : -- crashes in GC_malloc
      loadPackage "NumericalImplicitization"
--warning: symbol "Jacobian" in ReesAlgebra.Dictionary is shadowed by a symbol in NAGtypes.Dictionary
--  use the synonym ReesAlgebra$Jacobian

oo2 = NumericalImplicitization

oo2 : Package

ii3 : R = CC[x_(1,1)..x_(3,5)];

ii4 : F = (minors(3, genericMatrix(R, 3, 5)))_*;

ii5 : for i to 30 do numericalHilbertFunction(F, ideal 0_R, 2, Verbose => false)
-- warning: experimental computation over inexact field begun
--          results not reliable (one warning given per session)
GC_debug_free: found smashed location at 0x7a02788 in or near object at 0x79f6020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x78d9788 in or near object at 0x78cd020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x78d9788 in or near object at 0x78cd020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79bb788 in or near object at 0x79af020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79bb788 in or near object at 0x79af020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79bb788 in or near object at 0x79af020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79bb788 in or near object at 0x79af020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79c7788 in or near object at 0x79bb020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79c7788 in or near object at 0x79bb020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79c7788 in or near object at 0x79bb020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79c7788 in or near object at 0x79bb020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79c7788 in or near object at 0x79bb020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79bb788 in or near object at 0x79af020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79bb788 in or near object at 0x79af020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x7560788 in or near object at 0x7554020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_check_heap_block: found 1 smashed heap objects:
 0x75634c0 in or near object at 0x75634d0(<smashed>, appr. sz = 41)
GC_check_heap_block: found 1 smashed heap objects:
 0x75634c0 in or near object at 0x75634d0(<smashed>, appr. sz = 41)
GC_check_heap_block: found 1 smashed heap objects:
 0x75634c0 in or near object at 0x75634d0(<smashed>, appr. sz = 41)
GC_check_heap_block: found 1 smashed heap objects:
 0x75634c0 in or near object at 0x75634d0(<smashed>, appr. sz = 41)
GC_debug_free: found smashed location at 0x7761788 in or near object at 0x7755020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79bb788 in or near object at 0x79af020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x79bb788 in or near object at 0x79af020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x8182788 in or near object at 0x8176020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x824f788 in or near object at 0x8243020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x8190788 in or near object at 0x8184020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)
GC_debug_free: found smashed location at 0x8123788 in or near object at 0x8117020 (/mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2mem.c:96, sz=51040)

Thread 2 "M2-binary" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff258f700 (LWP 12038)]
0x00007ffff6b5c619 in GC_malloc () from /usr/lib/x86_64-linux-gnu/libgc.so.1
(gdb) where
#0  0x00007ffff6b5c619 in GC_malloc () from /usr/lib/x86_64-linux-gnu/libgc.so.1
#1  0x00007ffff6b4e93e in GC_debug_malloc () from /usr/lib/x86_64-linux-gnu/libgc.so.1
#2  0x00000000004ca80b in map_1 (a=0x8126520, f=0x25ffca0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors3.d:1420
#3  0x00000000004caaaf in map_1 (a=0x8126520, f=0x25fe6a0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors3.d:1431
#4  0x00000000004cbde2 in map_3 (e=0x7f5a890, f=0x25fe6a0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors3.d:1553
#5  0x00000000004cc924 in map_5 (e=0x7b7d720) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors3.d:1605
#6  0x000000000049a113 in evaluate_eval (c=0x25074d0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1270
#7  0x0000000000496f53 in evaluate_applyEEE (g=0x2509ca0, e0=0x25fe6a0, e1=0x7f5a890)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:936
#8  0x00000000004983a6 in evaluate_binarymethod (lhs=0x3a4ee60, rhs=0x3a4b110, methodkey=0x20fff60)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1054
#9  0x00000000004eebc6 in leftDividefun (lhs=0x3a4ee60, rhs=0x3a4b110)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors5.d:266
#10 0x0000000000499fe6 in evaluate_eval (c=0x3a4b160) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1262
#11 0x000000000049a860 in evaluate_eval (c=0x3a4b1b0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1302
#12 0x000000000048cc9d in evaluate_evalAllButTail (c=0x3a346e0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:41
#13 0x0000000000493766 in evaluate_applyFCC (fc=0x7b77060, ec=0x2583960)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:589
#14 0x000000000049a082 in evaluate_eval (c=0x2584d90) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1266
#15 0x000000000049aef3 in evaluate_eval (c=0x2584ed0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1331
#16 0x000000000049b7b8 in evaluate_eval (c=0x2583f20) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1371
#17 0x0000000000494f88 in evaluate_applyFCE (fc=0x7b770e0, e=0x7f3b840)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:738
#18 0x000000000049651a in evaluate_applyEE (f=0x7b770e0, e=0x7f3b840)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:891
#19 0x00000000004d1fbf in iteratedApply (e=0x7b77120) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors3.d:2097
#20 0x000000000049420b in evaluate_applyFCC (fc=0x39c6760, ec=0x388f1a0)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:658
#21 0x000000000049a082 in evaluate_eval (c=0x3890d90) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1266
#22 0x000000000049844c in evaluate_binarymethod_1 (left=0x5c9f1a0, rhs=0x3890d90, methodkey=0x20ff960)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1056
#23 0x000000000049a4b8 in evaluate_eval (c=0x3890de0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1282
#24 0x000000000049a388 in evaluate_eval (c=0x3890e30) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1279
#25 0x0000000000496f53 in evaluate_applyEEE (g=0x3892fa0, e0=0x5c9f1a0, e1=0x7f3b840)
---Type <return> to continue, or q <return> to quit---
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:936
#26 0x00000000004984f9 in evaluate_binarymethod_1 (left=0x5c9f1a0, rhs=0x290ac20, methodkey=0x20ff960)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1067
#27 0x000000000049a4b8 in evaluate_eval (c=0x7087cf0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1282
#28 0x0000000000491435 in evaluate_evalSequence (v=0x290ae60) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:406
#29 0x000000000049625f in evaluate_applyFCCS (c=0x4623260, cs=0x290ae60)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:773
#30 0x0000000000492fcd in evaluate_applyFCC (fc=0x4623260, ec=0x290aea0)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:558
#31 0x000000000049a2a0 in evaluate_eval (c=0x7087d90) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1277
#32 0x000000000049a860 in evaluate_eval (c=0x7087de0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1302
#33 0x000000000049b96a in evaluate_eval (c=0x28eaaa0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1377
#34 0x0000000000492021 in evaluate_applyFCS (c=0x7b70820, v=0x7f27480)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:518
#35 0x00000000004963a9 in evaluate_applyES (f=0x7b70820, v=0x7f27480)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:878
#36 0x00000000004f29ec in applyEOS (f=0x290cb20, o=0x61a8aa0, s=0x7f27480)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors5.d:729
#37 0x00000000004f3c6f in method1234o (e=0x7b708a0, env=0x5c0cd40) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors5.d:794
#38 0x000000000049a1df in evaluate_eval (c=0x2588430) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1274
#39 0x0000000000492b11 in evaluate_applyFCS (c=0x7b70920, v=0x7f27480)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:461
#40 0x0000000000496501 in evaluate_applyEE (f=0x7b70920, e=0x7f27480)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:890
#41 0x00000000004d1fbf in iteratedApply (e=0x7b70960) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors3.d:2097
#42 0x000000000049a113 in evaluate_eval (c=0x2525840) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1270
#43 0x0000000000492b11 in evaluate_applyFCS (c=0x28db720, v=0x61a8b60)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:461
#44 0x00000000004962ae in evaluate_applyFCCS (c=0x28db720, cs=0x5c99680)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:775
#45 0x0000000000492fcd in evaluate_applyFCC (fc=0x28db720, ec=0x290dee0)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:558
#46 0x000000000049a2a0 in evaluate_eval (c=0x70968e0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1277
#47 0x0000000000492021 in evaluate_applyFCS (c=0x7b70a20, v=0x7f27610)
---Type <return> to continue, or q <return> to quit---
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:518
#48 0x00000000004963a9 in evaluate_applyES (f=0x7b70a20, v=0x7f27610)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:878
#49 0x00000000004f29ec in applyEOS (f=0x290d860, o=0x61a8ce0, s=0x7f27610)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors5.d:729
#50 0x00000000004f427c in method1234o (e=0x7b70a60, env=0x5c0cd40) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors5.d:782
#51 0x000000000049a1df in evaluate_eval (c=0x2588430) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1274
#52 0x0000000000492b11 in evaluate_applyFCS (c=0x7b70aa0, v=0x7f27610)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:461
#53 0x0000000000496501 in evaluate_applyEE (f=0x7b70aa0, e=0x7f27610)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:890
#54 0x00000000004d1fbf in iteratedApply (e=0x7b70ae0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors3.d:2097
#55 0x000000000049a113 in evaluate_eval (c=0x2525840) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1270
#56 0x0000000000492b11 in evaluate_applyFCS (c=0x28db720, v=0x7f0b3e0)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:461
#57 0x00000000004962ae in evaluate_applyFCCS (c=0x28db720, cs=0x6988250)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:775
#58 0x0000000000492fcd in evaluate_applyFCC (fc=0x28db720, ec=0x2da5620)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:558
#59 0x000000000049a2a0 in evaluate_eval (c=0x69882a0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1277
#60 0x0000000000490ada in evalForCode (c=0x7400cd0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:361
#61 0x000000000049b356 in evaluate_eval (c=0x7400cd0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1353
#62 0x000000000049c05f in evaluate_evalexcept (c=0x7400cd0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1404
#63 0x0000000000565737 in readeval4 (file=0x6120c20, printout=1 '\001', dictionary=0x60fded0, returnLastvalue=0 '\000', 
    stopIfBreakReturnContinue=0 '\000', returnIfError=1 '\001') at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/interp.dd:180
#64 0x0000000000566815 in readeval3 (file=0x6120c20, printout=1 '\001', dc=0x6120ce0, returnLastvalue=0 '\000', 
    stopIfBreakReturnContinue=0 '\000', returnIfError=1 '\001') at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/interp.dd:274
#65 0x00000000005670e5 in loadprint (filename=0x6c7b570, dc=0x6120ce0, returnIfError=1 '\001')
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/interp.dd:345
#66 0x00000000005677b7 in input (e=0x6120ea0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/interp.dd:399
#67 0x000000000049a113 in evaluate_eval (c=0x24be390) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1270
#68 0x000000000049a860 in evaluate_eval (c=0x24be3e0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1302
#69 0x000000000049b7b8 in evaluate_eval (c=0x24c19a0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1371
#70 0x000000000049af1e in evaluate_eval (c=0x24be570) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1330
---Type <return> to continue, or q <return> to quit---
#71 0x000000000049b891 in evaluate_eval (c=0x24c1b20) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1374
#72 0x00000000004cf63d in scan_1 (a=0x6120fe0, f=0x6120f60) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors3.d:1732
#73 0x00000000004d171c in scan_4 (e=0x60f1020, f=0x6120f60) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors3.d:2032
#74 0x00000000004d19c6 in scan_5 (e=0x6120f20) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors3.d:2041
#75 0x000000000049a113 in evaluate_eval (c=0x24be660) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1270
#76 0x00000000004ab672 in EqualEqualEqualfun (lhs=0x24c1ca0, rhs=0x24be660)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/actors.d:708
#77 0x0000000000499fe6 in evaluate_eval (c=0x24be6b0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1262
#78 0x000000000049ae3f in evaluate_eval (c=0x24be700) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1328
#79 0x000000000049b96a in evaluate_eval (c=0x24c1d60) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1377
#80 0x0000000000495e1d in evaluate_applyFCCS (c=0x24c40e0, cs=0x24c3250)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:828
#81 0x0000000000492fcd in evaluate_applyFCC (fc=0x24c40e0, ec=0x24c7b20)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:558
#82 0x000000000049a082 in evaluate_eval (c=0x24c32a0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1266
#83 0x0000000000495e1d in evaluate_applyFCCS (c=0x24c7560, cs=0x24c9840)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:828
#84 0x0000000000492fcd in evaluate_applyFCC (fc=0x24c7560, ec=0x24cbaa0)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:558
#85 0x000000000049a082 in evaluate_eval (c=0x24c9890) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1266
#86 0x000000000048ca06 in evaluate_evalAllButTail (c=0x24cbba0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:32
#87 0x0000000000493766 in evaluate_applyFCC (fc=0x24cb7e0, ec=0x611f6e0)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:589
#88 0x000000000049a082 in evaluate_eval (c=0x60f1570) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1266
#89 0x000000000049c05f in evaluate_evalexcept (c=0x60f1570) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1404
#90 0x0000000000565737 in readeval4 (file=0x611fd60, printout=1 '\001', dictionary=0x60bb480, returnLastvalue=0 '\000', 
    stopIfBreakReturnContinue=0 '\000', returnIfError=0 '\000') at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/interp.dd:180
#91 0x0000000000566815 in readeval3 (file=0x611fd60, printout=1 '\001', dc=0x611fe20, returnLastvalue=0 '\000', 
    stopIfBreakReturnContinue=0 '\000', returnIfError=0 '\000') at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/interp.dd:274
#92 0x00000000005670e5 in loadprint (filename=0x21c0d40, dc=0x611fe20, returnIfError=0 '\000')
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/interp.dd:345
#93 0x0000000000567a7a in commandInterpreter_2 (e=0x20b6e00) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/interp.dd:462
#94 0x000000000049a113 in evaluate_eval (c=0x60bb750) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1270
#95 0x000000000049a860 in evaluate_eval (c=0x60bb7a0) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1302
---Type <return> to continue, or q <return> to quit---
#96 0x000000000049ba43 in evaluate_eval (c=0x6116c60) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1380
#97 0x000000000049c05f in evaluate_evalexcept (c=0x6116c60) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/evaluate.d:1404
#98 0x0000000000565737 in readeval4 (file=0x2239ea0, printout=0 '\000', dictionary=0x2236de0, returnLastvalue=0 '\000', 
    stopIfBreakReturnContinue=0 '\000', returnIfError=0 '\000') at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/interp.dd:180
#99 0x0000000000566815 in readeval3 (file=0x2239ea0, printout=0 '\000', dc=0x2239da0, returnLastvalue=0 '\000', 
    stopIfBreakReturnContinue=0 '\000', returnIfError=0 '\000') at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/interp.dd:274
#100 0x0000000000566918 in readeval (file=0x2239ea0, returnLastvalue=0 '\000', returnIfError=0 '\000')
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/interp.dd:284
#101 0x000000000056864e in interp_process () at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/interp.dd:597
#102 0x0000000000425e09 in interpFunc (vargs2=0x20bf520) at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/d/M2lib.c:605
#103 0x00000000008acac1 in ThreadTask::run (this=0x222dda0, thread=0x20bf4d0)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/system/supervisor.cpp:360
#104 0x00000000008ace3e in SupervisorThread::threadEntryPoint (this=0x20bf4d0)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/system/supervisor.cpp:422
#105 0x00000000008aceae in SupervisorThread::threadEntryPoint (st=0x20bf4d0)
    at /mike-raid/home/dan/src/M2/overnight/M2/Macaulay2/system/supervisor.hpp:96
#106 0x00007ffff6b5dde1 in GC_inner_start_routine () from /usr/lib/x86_64-linux-gnu/libgc.so.1
#107 0x00007ffff6b58c62 in GC_call_with_stack_base () from /usr/lib/x86_64-linux-gnu/libgc.so.1
#108 0x00007ffff64dd6ba in start_thread (arg=0x7ffff258f700) at pthread_create.c:333
#109 0x00007ffff5b8841d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by DanGrayson** [comment]
@jchen419

**Comment by DanGrayson** [comment]
I've commented out the corresponding example in e3aaef901448eb6d349275577073af0da9e7af4b

**Comment by antonleykin** [comment]
Is this still an issue?

**Comment by DanGrayson** [comment]
I'll check ...

**Comment by DanGrayson** [comment]
No longer a problem, closing.
